[general]
hotkey_main = "Ctrl+Alt+Space"

# [providers]

# [[providers.list]]
# type     = "mdx"
# enabled  = true
# priority = 1
# label    = "Vocabulary.com"
# path     = "vocabulary.com.mdx"   # change this to the real path on your machine


# [[providers.list]]
# type        = "deepl"
# enabled     = true
# priority    = 2
# label       = "DeepL"
# api_key     = ""
# source_lang = "auto"
# target_lang = "ZH"
